apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-new
  labels:
    app: nginx-new
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-new
  template:
    metadata:
      labels:
        app: nginx-new
    spec:
      containers:
      - name: nginx-new
        image: nginx:latest
        ports:
        - containerPort: 80
