apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: group-1
  namespace: flux-system
spec:
  interval: 10m
  path: ./group-1/  # Path from the repo root
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
