apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: group-1
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/dev-all-apps/group-1/  # Path from the repo root
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: group-cluster-1
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/dev-app-clusters/group-cluster  # Path from the repo root
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: group-cluster-2
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/dev-app-clusters/group-cluster-2 # Path from the repo root
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
