apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress # Ensures all resources are applied to this namespace

resources:
  - repo.yaml  # The HelmRepository file
  - release.yaml     # The HelmRelease file
